default_platform(:ios)

platform :ios do
	desc "Description of what the lane does"
	lane :beta do |params|
		environment = params[:environment] || "develop"
		build_number = params[:build_number] || "45"
		
		match(type: 'appstore', readonly: true)
		update_plist( # Advanced processing: find URL scheme for particular key and replace value
 			plist_path: "BusinessCard/Info.plist",
  			block: proc do |plist|
    			plist["environment"] = environment
  			end
		)

		increment_build_number(build_number: build_number)
		gym(export_method: 'app-store')
		pilot(
			changelog: changelog_from_git_commits(merge_commit_filtering: "exclude_merges")
			)
	end
end
