platform :ios, '12.1'

target 'Cards' do
	use_frameworks!

    pod 'LDSiOSKit', :path => '../LDSiOSKit'
    pod 'CardsKit', :path => '../CardsKit'
    pod 'LoginModule', :path => '../LoginModule'
#    pod 'SwiftyTesseract',    '~> 2.1.0'

    pod 'Firebase/Core'
    pod 'Firebase/MLVision'
    # If using an on-device API:
    pod 'Firebase/MLVisionTextModel'

	target 'CardsTests' do
		inherit! :search_paths


	end

	target 'CardsUITests' do
		inherit! :search_paths
	end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == 'TesseractOCRiOS'
#       target.build_configurations.each do |config|
#         config.build_settings['ENABLE_BITCODE'] = 'NO'
#       end
#       header_phase = target.build_phases().select do |phase|
#         phase.is_a? Xcodeproj::Project::PBXHeadersBuildPhase
#       end.first
      
#       duplicated_header_files = header_phase.files.select do |file|
#         file.display_name == 'config_auto.h'
#       end
      
#       duplicated_header_files.each do |file|
#         header_phase.remove_build_file file
#       end
#     end
#   end

end
