#platform :ios, '12.1'

target 'Cards' do
	use_frameworks!

	pod 'LDSiOSKit', :path => '../LDSiOSKit'
	pod 'CardsKit', :path => '../CardsKit'
	pod 'LoginModule', :path => '../LoginModule'

	target 'CardsTests' do
		inherit! :search_paths


end

target 'CardsUITests' do
	inherit! :search_paths


end

end
