#platform :ios, '12.1'

target 'Cards' do
	use_frameworks!

	pod 'CardsKit', :path => '../CardsKit'

	target 'CardsTests' do
		inherit! :search_paths


end

target 'CardsUITests' do
	inherit! :search_paths


end

end
